### Exc 0

In [18]:
import numpy as np

print(f"Version: {np.__version__}")

Version: 1.26.0


### Exc 1

In [19]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])
D = np.array([0.1, 0.3])

In [20]:
# Convert numerical values to boolean values with astype
print(np.all(A.astype(bool)))
print(np.all(B.astype(bool)))
print(np.all(C.astype(bool)))
print(np.all(D.astype(bool)))

True
False
False
True


### Exc 2

In [21]:
print(np.all(A.astype(bool), axis=1))
print(np.all(B.astype(bool), axis=1))
print(np.all(C.astype(bool), axis=1))

[ True  True]
[ True False]
[False  True]


### Exc 3

In [22]:
print(np.any(A.astype(bool)))
print(np.any(B.astype(bool)))
print(np.any(C.astype(bool)))
print(np.any(D.astype(bool)))

True
True
True
True


### Exc 4

In [23]:
two_digit_arr = np.arange(start=10, stop=100, step=1)

print(two_digit_arr)
print(two_digit_arr.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
(90,)


### Exc 5

In [24]:
# Array from Exc 4
print(two_digit_arr.reshape((10, 9)))

[[10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]
 [82 83 84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97 98 99]]


### Exc 6

In [25]:
# Creating a 6x6 matrix of data type int
matrix = np.eye(6, dtype=int)

print(matrix)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


### Exc 7

In [26]:
# Setting the seed
np.random.seed(10)

rand_arr = np.random.rand(30)

print(rand_arr)
print(rand_arr.shape)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
(30,)


### Exc 8

In [27]:
# Setting the seed
np.random.seed(20)

# Generating and reshaping 40 random numbers between 0 and 1
matrix = np.random.rand(40).reshape((10, 4))

print(matrix)
print(matrix.shape)

[[0.5881308  0.89771373 0.89153073 0.81583748]
 [0.03588959 0.69175758 0.37868094 0.51851095]
 [0.65795147 0.19385022 0.2723164  0.71860593]
 [0.78300361 0.85032764 0.77524489 0.03666431]
 [0.11669374 0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686 0.17878052]
 [0.77025193 0.49238104 0.63125307 0.83949792]
 [0.4610394  0.49794007 0.67941112 0.65078591]
 [0.26879524 0.06732467 0.77144514 0.48098413]
 [0.32920641 0.51064106 0.26362883 0.31051155]]
(10, 4)
