### MPAI Lab 4

#### Imports

In [1]:
import numpy as np

### Zadanie 1

In [2]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

In [3]:
array_mean = np.mean([A, B])
array_mean

3.9375

### Zadanie 2

In [4]:
C = np.multiply(A, B)
C

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

### Zadanie 3

In [5]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

In [6]:
array_sqrt = np.sqrt(A)
array_sqrt

array([[1.73205081, 2.        , 3.        , 1.41421356],
       [2.23606798, 1.73205081, 1.41421356, 2.23606798]])

### Zadanie 4

In [7]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

In [8]:
# Pythagorean theorem states that sin²θ+cos²θ is equal to 1
# Because of that, the formula to compare matrix A and B would be:
# sin(mat_A)² + cos(mat_A)² == B

result = np.allclose(a=np.sin(A)**2 + np.cos(A)**2, b=B)
result

True

### Zadanie 5

In [9]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])

In [10]:
multiplied_matrix = np.dot(a=A, b=B)
multiplied_matrix

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])