### MPAI Lab 4

#### Imports

In [92]:
import numpy as np

### Zadanie 1

In [93]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

In [94]:
array_mean = np.mean([A, B])
array_mean

3.9375

### Zadanie 2

In [95]:
C = np.multiply(A, B)
C

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

### Zadanie 3

In [96]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

In [97]:
array_sqrt = np.sqrt(A)
array_sqrt

array([[1.73205081, 2.        , 3.        , 1.41421356],
       [2.23606798, 1.73205081, 1.41421356, 2.23606798]])

### Zadanie 4

In [98]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

In [99]:
# Pythagorean identity formula: sin²θ+cos²θ = 1
# Because of that, the formula to compare matrix A and B would be:
# sin(mat_A)² + cos(mat_A)² == B

result = np.allclose(a=np.sin(A)**2 + np.cos(A)**2, b=B)
result

True

### Zadanie 5

In [100]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])

In [101]:
multiplied_matrix = np.dot(a=A, b=B)
multiplied_matrix

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

### Zadanie 6

In [102]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

In [103]:
matrix_determinant = np.linalg.det(A)
matrix_determinant

51.999999999999986

### Zadanie 7

In [104]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

In [105]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [106]:
eigenvalues

array([-9.24621125, -3.        ,  7.24621125])

In [107]:
eigenvectors

array([[-6.26164716e-01, -8.94427191e-01,  8.90159406e-01],
       [-3.13082358e-01,  2.82399734e-16,  4.45079703e-01],
       [ 7.14070855e-01,  4.47213595e-01, -9.75719719e-02]])

### Zadanie 8

In [108]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

In [109]:
inverse_matrix = np.linalg.inv(A)
inverse_matrix

array([[-0.21393035,  0.75621891,  0.23880597],
       [ 0.05970149,  0.04477612,  0.11940299],
       [ 0.09950249, -0.25870647, -0.13432836]])

### Zadanie 9

In [110]:
G = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

In [111]:
matrix_trace = np.trace(G)
matrix_trace

-5

### Zadanie 10

In [112]:
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

In [113]:
A.shape

(4, 2)

In [114]:
B.shape

(1, 8)

In [115]:
# Use the reshape method to change the shape of the matrix

B = B.reshape(4, 2)
B

array([[4, 0],
       [2, 1],
       [1, 0],
       [2, 9]])

In [116]:
# Multiply the matrix A and the reshaped matrix B

multiplied_matrix = np.multiply(A, B)
multiplied_matrix

array([[ 8,  0],
       [ 8,  2],
       [ 5,  0],
       [ 8, 18]])