In [2]:
import numpy as np

## Dane studenta

# Zadania do samodzielnego wykonania

## Ćwiczenie 1

Wygeneruj następującą tablicę numpy:

In [3]:
array = ([[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]])

Zapisz tablicę do pliku tekstowego o nazwie `array.txt` z dwoma miejscami po przecinku, załaduj plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsoli.

Wskazówka: Użyj funkcji `np.savetxt()` oraz `np.loadtxt()`.

### Miejsce na rozwiązanie

In [4]:
array = np.array([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11]])

np.savetxt('./array.txt', array)

loaded_array = np.loadtxt('./array.txt')
print(loaded_array)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## Ćwiczenie 2

Listę z zadania 1 wczytaj do nowej zmiennej, a następnie przekształć ją na listę a wynik wydrukuj w konsoli.
Wskazówka: Użyj metody `np.array.tolist()`.

### Miejsce na rozwiązanie

In [5]:
load = np.loadtxt('./array.txt')
load = load.tolist()
print(load)
print(type(load))

[[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0]]
<class 'list'>


## Ćwiczenie 3

Listę z zadania 1 przekształć zamieniająć pierwszy i ostatni wiersz ze sobą.

Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [6]:
load = np.loadtxt('./array.txt')
load[[0, -1]] = load[[-1, 0]]
print(load)

[[ 8.  9. 10. 11.]
 [ 4.  5.  6.  7.]
 [ 0.  1.  2.  3.]]


## Ćwiczenie 4

Następującą tablicę numpy:

In [7]:
array = ([[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]])

przekształć w tablicę poniżej:

In [8]:
array = ([[0., 0., 0., 0., 0., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 0., 0., 0., 0., 0.]])

Wydrukuj wynik do konsoli.
Wskazówka: Użyj funkcji `np.pad()`.

### Miejsce na rozwiązanie

In [9]:
array = np.array([[1., 1., 1., 1.],
                  [1., 1., 1., 1.],
                  [1., 1., 1., 1.],
                  [1., 1., 1., 1.]])
array = np.pad(array=array, pad_width=1)
print(array)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Ćwiczenie 5

Następującą tablicę numpy:

In [10]:
array = ([[0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0]])

przekształć w tablicę poniżej:

In [11]:
array = ([[10,  0, 10,  0, 10,  0],
          [ 5,  0,  5,  0,  5,  0],
          [10,  0, 10,  0, 10,  0],
          [ 5,  0,  5,  0,  5,  0],
          [10,  0, 10,  0, 10,  0],
          [ 5,  0,  5,  0,  5,  0]])

Wydrukuj wynik do konsoli.
Wskazówka: Użyj operatora wycinania i przypisz odpowiednie wartości.

### Miejsce na rozwiązanie

In [12]:
array = np.array([[0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0]])

pattern = np.tile([5, 0], 3)
array[::2, :] = pattern * 2
array[1::2, :] = pattern
print(array)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


## Ćwiczenie 6

Korzystając z funkcji poniżej wygeneruj dwie tablice A i B a następnie połącz je w jedną. Wynik wydrukuj w konsoli.

In [13]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

### Miejsce na rozwiązanie

In [14]:
C = np.concatenate((A, B))
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


## Ćwiczenie 7

Z podanych tablic A i B poniżej, wyodrębnij wspólne elementy (przecięcie) tablic. Wydrukuj wynik do konsoli.

In [15]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]]) 

Wskazówka: Użyj funkcji `np.intersect1d()`.

### Miejsce na rozwiązanie

In [16]:
common_elements = np.intersect1d(A, B)
print(common_elements)

[0 2 3]


## Ćwiczenie 8

Podano następującą tablicę numpy A. Znajdź unikalne wartości tej tablicy. Wydrukuj wynik do konsoli.

In [17]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

### Miejsce na rozwiązanie

In [18]:
unique_elements = np.unique(A)
print(unique_elements)

[1 2 4 5 7 9]


## Ćwiczenie 9

Podana jest poniższa tablica:

In [19]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

Zwróć indeksy z maksymalnymi wartościami dla danego wiersza. Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [20]:
print(np.max(a=A, axis=1))

[0.4 0.8 0.5]


## Ćwiczenie 10

Posortuj tablicę A:
- według wiersza (rosnąco),
- według kolumny (rosnąco).

In [21]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [22]:
print(np.sort(a=A, axis=1))
print()
print(np.sort(a=A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]

[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


## Ćwiczenie 11

Wyodrębnij wszystkie elementy tablicy A o wartości większej niż 8. Wydrukuj wynik do konsoli.

In [23]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

### Miejsce na rozwiązanie

In [24]:
condlist = A>8
choicelist = A
selection_array = np.select(condlist=condlist, choicelist=choicelist)
print(selection_array)

[14.99  9.99  9.99]


## Ćwiczenie 12

Podana jest następująca tablica A. Zastąp elementy większe niż 10 wartością stałą 10.

In [25]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [26]:
CONST = 10
A[A > 10] = CONST
print(A)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


## Ćwiczenie 13

Przedstaw poniższą dwuwymiarową tablicę A jako 'spłaszczoną' jednowymiarową tablicę. Wydrukuj wynik do konsoli.

In [27]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wskazówka: Użyj funkcji `np.ravel()`.

### Miejsce na rozwiązanie

In [28]:
print(np.ravel(a=A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


## Ćwiczenie 14

Zbuduj tablicę o tym samym kształcie i typie danych co tablica A i wypełnij ją stałą wartością 0.0. Wydrukuj wynik do konsoli.

In [29]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wskazówka: Użyj funkcji `np.zeros_like()`.

### Miejsce na rozwiązanie

In [30]:
A_duplicate = np.zeros_like(a=A, dtype=type(A))
print(A_duplicate)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Ćwiczenie 15

Zbuduj tablicę o tym samym kształcie i typie danych co tablica A i wypełnij ją stałą wartością 19.99. Wydrukuj wynik do konsoli.

In [31]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wskazówka: Użyj funkcji `np.full_like()`.

### Miejsce na rozwiązanie

In [32]:
A_duplicate_filled = np.full_like(a=A, dtype=type(A), fill_value=19.99)
print(A_duplicate_filled)

[[19.99 19.99 19.99]
 [19.99 19.99 19.99]
 [19.99 19.99 19.99]]


## Ćwiczenie 16

Zbuduj dwuwymiarową tablicę - macierz dolna trójkątna. Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [33]:
triangle_array = np.tri(N=8, M=8)
print(triangle_array)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


## Ćwiczenie 17

Utwórz dowolną trójwymiarową tablicę o kształcie (2, 3, 4) i przypisz do zmiennej PBS. A następnie zapisz ją do pliku `array.npy`

### Miejsce na rozwiązanie

In [34]:
PBS = np.zeros(shape=(2, 3, 4))
print(PBS)

np.save(file='./array.npy', arr=PBS)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Ćwiczenie 18

Wygeneruj dwuwymiarową tablicę o kształcie (200, 300) wypełnioną losowymi wartościami od 0 do 255 (włącznie) o typie danych np.uint8 i przypisz do zmiennej image.

### Miejsce na rozwiązanie

In [35]:
image = np.random.randint(low=0, high=256, dtype=np.uint8, size=(200, 300))
print(image)

[[223 182  67 ...  72  75 128]
 [ 19   4 181 ... 125  56 129]
 [ 22 167  29 ...  43  93 172]
 ...
 [ 54  67 243 ...  65 230  82]
 [ 23 147 137 ... 140 227  30]
 [227  28 108 ...  44 210  19]]


## Ćwiczenie 19

Posortuj tablicę image wzdłuż wiersza rosnąco i przypisz do zmiennej image_sorted.

### Miejsce na rozwiązanie

In [36]:
image_sorted = np.sort(a=image, axis=1)
print(image_sorted)

[[  1   1   2 ... 252 253 254]
 [  0   0   1 ... 252 253 254]
 [  0   1   3 ... 254 255 255]
 ...
 [  0   0   1 ... 253 254 255]
 [  0   1   2 ... 247 250 252]
 [  0   0   1 ... 252 253 255]]


## Ćwiczenie 20

Wygeneruj dwuwymiarową tablicę o kształcie (200, 300) wypełnioną losowymi wartościami od 0 do 255 (włącznie) o typie danych np.float32 i przypisz do zmiennej. Następnie zapisz tablicę do pliku binarnego o nazwie `array_20.npy`, załaduj ten plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsoli.

Wskazówka: Użyj funkcji `np.save()` oraz `np.load()`.

### Miejsce na rozwiązanie

In [37]:
array = np.random.uniform(low=0, high=256, size=(200, 300)).astype(np.float32)
np.save('./array_20.npy', arr=array)

In [38]:
array_20 = np.load('./array_20.npy')
print(array_20)

[[184.40771   174.81168    23.958612  ... 161.4316    152.08731
   24.123705 ]
 [  1.8264441  98.51526    32.61408   ...  61.132362  145.1893
  203.91135  ]
 [105.522675    7.9135895  30.128225  ... 232.81366   214.61806
  235.48502  ]
 ...
 [253.83255    29.365227  138.30257   ...  47.667545  230.11485
  158.57875  ]
 [ 58.189857   45.944805   72.81693   ... 179.41757   226.03851
  106.43628  ]
 [240.22142   201.82227   144.60806   ... 254.16457    72.4219
   20.162348 ]]


# Wnioski i sugestie do ćwiczeń