### MPAI Lab 3

#### Imports

In [43]:
import numpy as np

### Zadanie 1

In [44]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

In [45]:
C = np.concatenate((A, B))
C

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

### Zadanie 2

In [46]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

In [47]:
new_array = np.concatenate((data, target), axis=1)
new_array

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### Zadanie 3

In [48]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

In [49]:
stacked_features = np.column_stack(tup=(feature1, feature2, feature3))
stacked_features = np.concatenate(stacked_features)
stacked_features

array([1.6, 0.4, 1.4, 0.9, 1.3, 0.3, 2.2, 3.2, 1.2])

### Zadanie 4

In [50]:
np.random.seed(42)

A = np.random.randint(low=0 ,high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])

In [51]:
A1, A2, A3 = np.split(ary=A, indices_or_sections=[2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [52]:
# Select a single row of ones

ones_row = A3[1, :]
print(f'Set of ones: {ones_row}')

# Select a column of zeros

zeros_row = A1[0, :]
print(f'Row of zeros: {zeros_row}')

# Drop the last two columns

A = A[:, :-2]

# Repeat the pattern of ones to fill the center of the transformed array

A[1:5, 1:5] = np.repeat(a=ones_row, repeats=2)

# Fill in the first and last rows with zeros

A[0, :] = np.repeat(a=zeros_row, repeats=3)

# Append the matrix with values from the first row

A = np.vstack(tup=[A, A[0, :]])

# Copy values from the first column to the last column

A[:, -1] = A[:, 0]

print(f'Transformed matrix:\n{A}')
print(f'Transformed matrix shape: {A.shape}')

Set of ones: [1 1]
Row of zeros: [0 0]
Transformed matrix shape: (6, 6)
Transformed matrix:
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


### Zadanie 5

In [53]:
np.random.seed(42)

A = np.random.randint(low=0 ,high=2, size=(10, 6))

In [54]:
positive_values_count = (A > 0).sum()
positive_values_count

31

### Zadanie 6

In [55]:
np.random.seed(42)

A = np.random.randn(10, 4)

In [56]:
np.set_printoptions(precision=4)

A

array([[ 0.4967, -0.1383,  0.6477,  1.523 ],
       [-0.2342, -0.2341,  1.5792,  0.7674],
       [-0.4695,  0.5426, -0.4634, -0.4657],
       [ 0.242 , -1.9133, -1.7249, -0.5623],
       [-1.0128,  0.3142, -0.908 , -1.4123],
       [ 1.4656, -0.2258,  0.0675, -1.4247],
       [-0.5444,  0.1109, -1.151 ,  0.3757],
       [-0.6006, -0.2917, -0.6017,  1.8523],
       [-0.0135, -1.0577,  0.8225, -1.2208],
       [ 0.2089, -1.9597, -1.3282,  0.1969]])

### Zadanie 7

In [57]:
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(precision=8, suppress=True)
np.intersect1d(ar1=A, ar2=A)
A

array([0.0000012 , 0.00000017])

### Zadanie 8

In [58]:
np.random.seed(42)

A = np.random.randn(8, 4)

In [59]:
A = np.delete(arr=A, obj=2, axis=1)
A

array([[ 0.49671415, -0.1382643 ,  1.52302986],
       [-0.23415337, -0.23413696,  0.76743473],
       [-0.46947439,  0.54256004, -0.46572975],
       [ 0.24196227, -1.91328024, -0.56228753],
       [-1.01283112,  0.31424733, -1.4123037 ],
       [ 1.46564877, -0.2257763 , -1.42474819],
       [-0.54438272,  0.11092259,  0.37569802],
       [-0.60063869, -0.29169375,  1.85227818]])

### Zadanie 9

In [60]:
v = np.array([3, 4, -2])

In [61]:
norm = np.linalg.norm(x=v)
norm

5.385164807134504

### Zadnie 10

In [62]:
A = np.random.randint(10, size=(100, 30))

In [63]:
np.set_printoptions(edgeitems=10)
A

array([[6, 7, 2, 0, 3, 1, 7, 3, 1, 5, ..., 6, 8, 7, 4, 1, 4, 7, 9, 8, 8],
       [0, 8, 6, 8, 7, 0, 7, 7, 2, 0, ..., 8, 7, 1, 0, 6, 6, 7, 4, 2, 7],
       [5, 2, 0, 2, 4, 2, 0, 4, 9, 6, ..., 6, 6, 3, 6, 2, 5, 1, 9, 8, 4],
       [5, 3, 9, 6, 8, 6, 0, 0, 8, 8, ..., 9, 7, 5, 7, 8, 3, 0, 0, 9, 3],
       [6, 1, 2, 0, 4, 0, 7, 0, 0, 1, ..., 5, 6, 3, 6, 7, 0, 5, 7, 4, 3],
       [1, 5, 5, 0, 8, 5, 2, 3, 3, 2, ..., 1, 7, 0, 8, 8, 1, 6, 9, 2, 6],
       [9, 8, 3, 0, 1, 0, 4, 4, 6, 8, ..., 3, 0, 7, 3, 5, 7, 3, 2, 8, 2],
       [8, 1, 1, 1, 5, 2, 8, 3, 0, 3, ..., 5, 6, 5, 5, 5, 2, 5, 7, 1, 4],
       [0, 0, 4, 2, 3, 2, 0, 0, 4, 5, ..., 6, 0, 2, 1, 8, 9, 5, 9, 2, 7],
       [7, 1, 5, 6, 1, 9, 1, 9, 0, 7, ..., 7, 9, 6, 8, 3, 3, 0, 7, 2, 6],
       ...,
       [1, 2, 7, 7, 6, 5, 8, 3, 0, 7, ..., 4, 4, 3, 3, 0, 6, 8, 2, 1, 2],
       [0, 5, 6, 1, 7, 5, 3, 4, 7, 2, ..., 8, 2, 2, 2, 9, 2, 8, 3, 6, 8],
       [6, 8, 2, 3, 7, 5, 4, 3, 7, 0, ..., 3, 7, 1, 8, 5, 8, 7, 6, 0, 2],
       [1, 4, 4, 4, 3, 4, 